### ISSUE TITLE
Problem with Plot generation

### ISSUE THREAD

**Issue by PiresAllanSilva** [snandiDS/prokseq-v2.0#4]
During the run in docker this error occurs:

Traceback (most recent call last):
  File "scripts/prokseq.py", line 711, in <module>
    main()
  File "scripts/prokseq.py", line 600, in main
    fn.createGeneBodyPlot(rList)
  File "/root/prokseq/scripts/libmod/pipeFunc.py", line 235, in createGeneBodyPlot
    VAL = AR[1].rstrip().split(",")
IndexError: list index out of range

What should I do?

**Comment by snandiDS** [comment]
I doubt something's wrong with the input files. Please check them once
again. Let us know if the problem persists.

**Comment by PiresAllanSilva** [comment]
Hi, all
I'd solve the problem by replacing the genome file.
Now i'm having a new problem with DeSeq:

_Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 6 elements
Calls: read.table -> scan
Execution halted_

Would you help me?

**Comment by PiresAllanSilva** [comment]
The problem is at DESeq2 script. 
_cd1 <- read.table(sample, sep = " ", skip = 12)_
sep should be: ""
But after the modifications on script the prokseq.py overwrite my modifications.

**Comment by snandiDS** [comment]
I think sep=" " is correct. The code looks for a sample file which is as
follows.

###################################################################################
#       File "sample" - sample description file
#       Specify the names of the sample files and tag them as "treat" and
"control".
###################################################################################
#       Specify the genome file, and specify the path where the
#       indexed file will be stored, and the prifex of the indexed genome.
#       Default is 'bowtie2_genome'.
GENOME SequenceChromosome.fasta bowtie2_genome/sequenceChr
#       Specify the fastq files
#       Specify the output name of the sam files.
#       Followed by the tag/class/condition of the sample (treated or
control)
#       List all the fastq files as bellow.
FASTQ sampleTreat_1.R1.fq sampleTreat_1.R2.fq sampleTreat_1.sam treat
FASTQ sampleTreat_2.R1.fq sampleTreat_2.R2.fq sampleTreat_2.sam treat
FASTQ sampleTreat_3.R1.fq sampleTreat_3.R2.fq sampleTreat_3.sam treat
FASTQ sampleCtrl_1.R1.fq sampleCtrl_1.R2.fq sampleCtrl_1.sam control
FASTQ sampleCtrl_2.R1.fq sampleCtrl_2.R2.fq sampleCtrl_2.sam control
FASTQ sampleCtrl_3.R1.fq sampleCtrl_3.R2.fq sampleCtrl_3.sam control
#
#       End of file "sample"
#
Please check if you are providing single-end sample files while running
paired-end.
Hope this helps.

**Comment by kirkgrubbs1** [comment]
> Hi, all I'd solve the problem by replacing the genome file. Now i'm having a new problem with DeSeq:
> 
> _Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 1 did not have 6 elements Calls: read.table -> scan Execution halted_
> 
> Would you help me?

I'm having the same issue with the plot generation step. Did you figure out what was wrong with your genome file?

**Comment by plwalker12** [comment]
If you are unable to complete the GeneBodyPlot it's because the fasta, BED, and/or GTF files that you are using as the input do not match (leading to the index error).
Make sure you are obtaining the FASTA and GTF from the same source (same version) and then convert that GTF to the BED file to assure they match.
